# Generated by Django 5.2.14 on 2026-05-19 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projectmember",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="members",
            field=models.ManyToManyField(
                related_name="projects",
                through="projects.ProjectMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="column",
            index=models.Index(
                fields=["board", "position"], name="columns_board_i_edff8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["project", "position"], name="boards_project_ee3a42_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="projectmember",
            unique_together={("user", "project")},
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="projects_organiz_d764bf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(fields=["key"], name="projects_key_173443_idx"),
        ),
    ]
